Cargo.lock: downgrade `rayon` to 1.7.0
The latest version requires Rust 1.63, which is higher than `pbkdf2`'s
MSRV:

https://github.com/RustCrypto/password-hashes/actions/runs/6794257921/job/18470364231?pr=471

error: package `rayon-core v1.12.0` cannot be built because it requires rustc 1.63 or newer, while the currently active rustc version is 1.60.0
Error: Process completed with exit code 101.